#!/bin/bash
source ~/anaconda3/etc/profile.d/conda.sh
conda activate research


# EMNIST 3 SEEDS SHARP
python launch.py --experiment_name "EMNIST_SHARP_SEED0_Activation_Replay" --gpu_prefetch "1" --ltm_per_class "25" --ltm_k_nearest "5" --stm_per_class "25" --stm_num_tasks "1" --memory_mode "internal" --dataset "EMNIST" --number_of_tasks "13" --model "MNISTLIKE" --prune_perc "60.0" --seed "0" --permute_seed "0" --deterministic "1" --optimizer "Adadelta" --sgd_momentum "0.9" --learning_rate "1.0" --batch_size "512" --batch_size_memory "512" --weight_decay "0.0" --last_layer_bn "0" --supcon_temperature "0.05" --reinit "1" --lr_decay_phase "1.0" --phase_epochs "3" --early_stop_coef "2.0" --min_activation_perc "40.0" --max_phases "15" --tau_param "30.0" --pretrain_load_path "./Store/conv_layers_early_mnist_supcon.pth" --pretrain_freeze "1" --verbose_logging "4"
python launch.py --experiment_name "EMNIST_SHARP_SEED1_Activation_Replay" --gpu_prefetch "1" --ltm_per_class "25" --ltm_k_nearest "5" --stm_per_class "25" --stm_num_tasks "1" --memory_mode "internal" --dataset "EMNIST" --number_of_tasks "13" --model "MNISTLIKE" --prune_perc "60.0" --seed "1" --permute_seed "0" --deterministic "1" --optimizer "Adadelta" --sgd_momentum "0.9" --learning_rate "1.0" --batch_size "512" --batch_size_memory "512" --weight_decay "0.0" --last_layer_bn "0" --supcon_temperature "0.05" --reinit "1" --lr_decay_phase "1.0" --phase_epochs "3" --early_stop_coef "2.0" --min_activation_perc "40.0" --max_phases "15" --tau_param "30.0" --pretrain_load_path "./Store/conv_layers_early_mnist_supcon.pth" --pretrain_freeze "1" --verbose_logging "4"
python launch.py --experiment_name "EMNIST_SHARP_SEED2_Activation_Replay" --gpu_prefetch "1" --ltm_per_class "25" --ltm_k_nearest "5" --stm_per_class "25" --stm_num_tasks "1" --memory_mode "internal" --dataset "EMNIST" --number_of_tasks "13" --model "MNISTLIKE" --prune_perc "60.0" --seed "2" --permute_seed "0" --deterministic "1" --optimizer "Adadelta" --sgd_momentum "0.9" --learning_rate "1.0" --batch_size "512" --batch_size_memory "512" --weight_decay "0.0" --last_layer_bn "0" --supcon_temperature "0.05" --reinit "1" --lr_decay_phase "1.0" --phase_epochs "3" --early_stop_coef "2.0" --min_activation_perc "40.0" --max_phases "15" --tau_param "30.0" --pretrain_load_path "./Store/conv_layers_early_mnist_supcon.pth" --pretrain_freeze "1" --verbose_logging "4"


# CIFAR100 3 SEEDS SHARP
python launch.py --experiment_name "CIFAR100_SHARP_SEED0_Activation_Replay" --gpu_prefetch "1" --ltm_per_class "50" --ltm_k_nearest "5" --stm_per_class "100" --stm_num_tasks "1" --memory_mode "internal" --dataset "SplitCIFAR100" --number_of_tasks "10" --model "VGG_Small" --prune_perc "60.0" --seed "0" --permute_seed "0" --deterministic "1" --optimizer "Adadelta" --sgd_momentum "0.9" --learning_rate "1.0" --batch_size "64" --batch_size_memory "64" --weight_decay "0.0" --last_layer_bn "0" --supcon_temperature "0.05" --reinit "1" --lr_decay_phase "1.0" --phase_epochs "5" --early_stop_coef "2.0" --min_activation_perc "70.0" --max_phases "15" --tau_param "30.0" --pretrain_load_path "./Store/conv_layers_early_cifar10_supcon.pth" --pretrain_freeze "1" --verbose_logging "4"
python launch.py --experiment_name "CIFAR100_SHARP_SEED1_Activation_Replay" --gpu_prefetch "1" --ltm_per_class "50" --ltm_k_nearest "5" --stm_per_class "100" --stm_num_tasks "1" --memory_mode "internal" --dataset "SplitCIFAR100" --number_of_tasks "10" --model "VGG_Small" --prune_perc "60.0" --seed "1" --permute_seed "0" --deterministic "1" --optimizer "Adadelta" --sgd_momentum "0.9" --learning_rate "1.0" --batch_size "64" --batch_size_memory "64" --weight_decay "0.0" --last_layer_bn "0" --supcon_temperature "0.05" --reinit "1" --lr_decay_phase "1.0" --phase_epochs "5" --early_stop_coef "2.0" --min_activation_perc "70.0" --max_phases "15" --tau_param "30.0" --pretrain_load_path "./Store/conv_layers_early_cifar10_supcon.pth" --pretrain_freeze "1" --verbose_logging "4"
python launch.py --experiment_name "CIFAR100_SHARP_SEED2_Activation_Replay" --gpu_prefetch "1" --ltm_per_class "50" --ltm_k_nearest "5" --stm_per_class "100" --stm_num_tasks "1" --memory_mode "internal" --dataset "SplitCIFAR100" --number_of_tasks "10" --model "VGG_Small" --prune_perc "60.0" --seed "2" --permute_seed "0" --deterministic "1" --optimizer "Adadelta" --sgd_momentum "0.9" --learning_rate "1.0" --batch_size "64" --batch_size_memory "64" --weight_decay "0.0" --last_layer_bn "0" --supcon_temperature "0.05" --reinit "1" --lr_decay_phase "1.0" --phase_epochs "5" --early_stop_coef "2.0" --min_activation_perc "70.0" --max_phases "15" --tau_param "30.0" --pretrain_load_path "./Store/conv_layers_early_cifar10_supcon.pth" --pretrain_freeze "1" --verbose_logging "4"
